/**
 * MediLink CARE - Canonical System Constants & Enums
 */

const ROLES = Object.freeze({
  PATIENT: 'PATIENT',
  HOSPITAL: 'HOSPITAL',
  AMBULANCE: 'AMBULANCE',
  ADMIN: 'ADMIN',
  SYSTEM_DOCTOR: 'SYSTEM_DOCTOR'
});

const REQUEST_TYPES = Object.freeze({
  PATIENT_ADMISSION: 'PATIENT_ADMISSION',
  HOSPITAL_TRANSFER: 'HOSPITAL_TRANSFER',
  BLOOD_REQUEST: 'BLOOD_REQUEST',
  EQUIPMENT_REQUEST: 'EQUIPMENT_REQUEST',
  AMBULANCE_REQUEST: 'AMBULANCE_REQUEST'
});

const REQUEST_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
  RESOLVED: 'RESOLVED',
  CANCELLED: 'CANCELLED'
});

const APPOINTMENT_STATUSES = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
  FOLLOW_UP: 'FOLLOW_UP'
});

const AMBULANCE_STATUSES = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  ON_DUTY: 'ON_DUTY',
  OFFLINE: 'OFFLINE'
});

const AMBULANCE_TRIP_STATUSES = Object.freeze({
  PENDING: 'Pending',
  ON_THE_WAY: 'On the Way',
  ARRIVED: 'Arrived',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled'
});

const BLOOD_GROUPS = Object.freeze(['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']);

const PRIORITIES = Object.freeze({
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
  EMERGENCY: 'EMERGENCY'
});

module.exports = {
  ROLES,
  REQUEST_TYPES,
  REQUEST_STATUSES,
  APPOINTMENT_STATUSES,
  AMBULANCE_STATUSES,
  AMBULANCE_TRIP_STATUSES,
  BLOOD_GROUPS,
  PRIORITIES
};
